nodeLinker: node-modules
npmScopes:
  '@react-scrollytelling':
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'
    npmRegistryServer: 'https://registry.npmjs.org'
npmRegistries:
  'https://registry.npmjs.org/':
    npmAuthToken: '${NPM_TOKEN}'
