compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://registry.npmjs.org/":
    npmAuthToken: "${NPM_TOKEN}"

npmScopes:
  "@react-scrollytelling":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"
