packages:
  - "packages/*"
  - "apps/*"

catalogs:
  default:
    react: ^19.2.4
    react-dom: ^19.2.4
    "@types/react": ^19.2.10
    "@types/react-dom": ^19.2.3
    motion: ^12.34.3
    jest: ^29.7.0
    ts-jest: ^29.2.4
    jest-environment-jsdom: ^29.7.0
    "@testing-library/dom": ^10.4.0
    "@testing-library/jest-dom": ^6.4.8
    "@testing-library/react": ^16.0.0
    "@react-spring/web": ^10.0.3
